# Introduction to NumPy

The most fundamental third-party package for scientific computing in Python is NumPy, which provides multidimensional array data types, along with associated functions and methods to manipulate them. Other third-party packages, including Pandas, use NumPy arrays as backends for more specialized data structures.


While Python comes with several container types (`list`,`tuple`,`dict`), NumPy's arrays are implemented closer to the hardware, and are therefore more efficient than the built-in types. This is particularly true for large data, for which NumPy scales much better than Python's built-in data structures.


NumPy arrays also retain a suite of associated functions and methods that allow for efficient *array-oriented* computing.


## Basics of Numpy arrays

We now turn our attention to the Numpy library, which forms the base layer for the entire 'scipy ecosystem'.  Once you have installed numpy, you can import it as

In [2]:
import numpy

though we will employ the common shorthand

In [3]:
import numpy as np

As mentioned above, the main object provided by numpy is a powerful array.  We'll start by exploring how the numpy array differs from Python lists.  We start by creating a simple list and an array with the same contents of the list:

In [13]:
lst = list(range(1000))
arr = np.arange(1000)

# Here's what the array looks like
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(arr)

numpy.ndarray

In [15]:
%timeit [i**2 for i in lst]

1000 loops, best of 3: 402 µs per loop


In [16]:
%timeit arr**2

The slowest run took 16.63 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.53 µs per loop


Elements of a one-dimensional array are indexed with square brackets, as with lists:

In [17]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [18]:
arr[-1]

999

The first difference to note between lists and arrays is that arrays are *homogeneous*; i.e. all elements of an array must be of the same type.  In contrast, lists can contain elements of arbitrary type. For example, we can change the last element in our list above to be a string:

In [19]:
lst[0] = 'a string inside a list'
lst[:10]

['a string inside a list', 1, 2, 3, 4, 5, 6, 7, 8, 9]

but the same can not be done with an array, as we get an error message:

In [20]:
arr[0] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

The information about the type of an array is contained in its *dtype* attribute:

In [21]:
arr.dtype

dtype('int64')

Once an array has been created, its dtype is fixed and it can only store elements of the same type.  For this example where the dtype is integer, if we store a floating point number it will be automatically converted into an integer:

In [22]:
arr[0] = 1.234
arr[:10]

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Above we created an array from an existing list; now let us now see other ways in which we can create arrays, which we'll illustrate next.  A common need is to have an array initialized with a constant value, and very often this value is 0 or 1 (suitable as starting value for additive and multiplicative loops respectively); `zeros` creates arrays of all zeros, with any desired dtype:

In [23]:
np.zeros(5, float)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
np.zeros(3, int)

array([0, 0, 0])

In [25]:
np.zeros(3, complex)

array([ 0.+0.j,  0.+0.j,  0.+0.j])

and similarly for `ones`:

In [26]:
print('5 ones: {0}'.format(np.ones(5)))

5 ones: [ 1.  1.  1.  1.  1.]


If we want an array initialized with an arbitrary value, we can create an empty array and then use the fill method to put the value we want into the array:

In [27]:
a = np.empty(4)
a

array([ -3.10503618e+231,  -3.10503618e+231,   2.19342406e-314,
         2.78136426e-309])

In [28]:
a.fill(5.5)
a

array([ 5.5,  5.5,  5.5,  5.5])

In [29]:
%timeit np.empty(1000)

The slowest run took 9.56 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 964 ns per loop


In [30]:
%timeit np.ones(1000)

The slowest run took 8.90 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 3.1 µs per loop


In [119]:
%timeit np.empty(1000).fill(1)

The slowest run took 13.59 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.74 µs per loop


In [118]:
%timeit np.ones(1000)*5.5

The slowest run took 78.37 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.61 µs per loop


We have seen how the `arange` function generates an array for a range of integers. Relatedly,  the `linspace` and `logspace` functions to create linearly and logarithmically-spaced grids respectively, with a fixed number of points and including both ends of the specified interval:

In [31]:
np.linspace(0, 1, num=5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [32]:
np.logspace(1, 4, num=4)

array([    10.,    100.,   1000.,  10000.])

Finally, it is often useful to create arrays with random numbers that follow a specific distribution.  The `np.random` module contains a number of functions that can be used to this effect, for example this will produce an array of 5 random samples taken from a standard normal distribution (0 mean and variance 1):

In [33]:
np.random.randn(5)

array([-0.07064572,  0.72655705, -2.17321124,  0.50059314, -0.67710859])

whereas this will also give 5 samples, but from a normal distribution with a mean of 9 and a standard deviation of 3:

In [145]:
norm10 = np.random.normal(loc=9, scale=3, size=10)

## Exercise

Generate a NumPy array of 1000 random numbers sampled from a Poisson distribution, with parameter `lam=5`. What is the modal value in the sample?

In [146]:
# Write your answer here

## Indexing with other arrays

Above we saw how to index arrays with single numbers and slices, just like Python lists.  But arrays allow for a more sophisticated kind of indexing which is very powerful: you can index an array with another array, and in particular with an array of boolean values.  This is particluarly useful to extract information from an array that matches a certain condition.

Consider for example that in the array `norm10` we want to replace all values above 9 with the value 0.  We can do so by first finding the *mask* that indicates where this condition is `True` or `False`:

In [147]:
norm10

array([  6.29831862,  12.72202318,  11.23394   ,   9.82478874,
         9.63633724,  11.87082172,   4.10450197,   8.21488151,
         7.03307727,  12.10920759])

In [148]:
mask = norm10 > 9
mask

array([False,  True,  True,  True,  True,  True, False, False, False,  True], dtype=bool)

Now that we have this mask, we can use it to either read those values or to reset them to 0:

In [149]:
norm10[mask]

array([ 12.72202318,  11.23394   ,   9.82478874,   9.63633724,
        11.87082172,  12.10920759])

In [150]:
norm10[mask] = 0
norm10

array([ 6.29831862,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  4.10450197,  8.21488151,  7.03307727,  0.        ])

## Multidimensional Arrays

Numpy can create arrays of aribtrary dimensions, and all the methods illustrated in the previous section work with more than one dimension. For example, a list of lists can be used to initialize a two dimensional array:

In [41]:
lst2 = [[1, 2], [3, 4]]
arr2 = np.array([[1, 2], [3, 4]])
arr2.shape

(2, 2)

With two-dimensional arrays we start seeing the power of numpy: while a nested list can be indexed using repeatedly the `[ ]` operator, multidimensional arrays support a much more natural indexing syntax with a single `[ ]` and a set of indices separated by commas:

In [42]:
lst2[0][1]


2

In [43]:
arr2[0,1]

2

Most of the array creation functions listed above can be used with more than one dimension, for example:

In [44]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
np.random.normal(10, 3, size=(2, 4))

array([[ 14.33053022,  18.2454981 ,  10.38232861,   6.72217819],
       [  6.99173095,  11.16929715,   7.59509797,   9.00733421]])

In fact, the shape of an array can be changed at any time, as long as the total number of elements is unchanged.  For example, if we want a 2x4 array with numbers increasing from 0, the easiest way to create it is via the numpy array's `reshape` method.

In [101]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

With multidimensional arrays, you can also use slices, and you can mix and match slices and single indices in the different dimensions (using the same array as above):

In [102]:
arr[1, 2:4]

array([6, 7])

In [103]:
arr[:, 2]

array([2, 6])

If you only provide one index, then you will get the corresponding row.

In [104]:
arr[1]

array([4, 5, 6, 7])

Now that we have seen how to create arrays with more than one dimension, it's a good idea to look at some of the most useful properties and methods that arrays have.  The following provide basic information about the size, shape and data in the array:

In [106]:
print('Data type                :', arr.dtype)
print('Total number of elements :', arr.size)
print('Number of dimensions     :', arr.ndim)
print('Shape (dimensionality)   :', arr.shape)
print('Memory used (in bytes)   :', arr.nbytes)

Data type                : int64
Total number of elements : 8
Number of dimensions     : 2
Shape (dimensionality)   : (2, 4)
Memory used (in bytes)   : 64


Arrays also have many useful methods, some especially useful ones are:

In [107]:
print('Minimum and maximum             :', arr.min(), arr.max())
print('Sum and product of all elements :', arr.sum(), arr.prod())
print('Mean and standard deviation     :', arr.mean(), arr.std())

Minimum and maximum             : 0 7
Sum and product of all elements : 28 0
Mean and standard deviation     : 3.5 2.29128784748


For these methods, the above operations area all computed on all the elements of the array.  But for a multidimensional array, it's possible to do the computation along a single dimension, by passing the `axis` parameter; for example:

In [108]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
arr.sum(axis=0)

array([ 4,  6,  8, 10])

In [110]:
arr.sum(axis=1)

array([ 6, 22])

As you can see in this example, the value of the `axis` parameter is the dimension which will be *consumed* once the operation has been carried out.  This is why to sum along the rows we use `axis=0`.  

This can be easily illustrated with an example that has more dimensions; we create an array with 4 dimensions and shape `(3,4,5,6)` and sum along the axis number 2 (i.e. the *third* axis, since in Python all counts are 0-based).  That consumes the dimension whose length was 5, leaving us with a new array that has shape `(3,4,6)`:

In [55]:
np.zeros((3,4,5,6)).sum(2).shape

(3, 4, 6)

Another widely used property of arrays is the `.T` attribute, which allows you to access the transpose of the array:

In [111]:
np.transpose(arr)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [112]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

There is a wide variety of methods and properties of arrays.       

In [58]:
[attr for attr in dir(arr) if not attr.startswith('__')]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

You can access the documentation for any of them using the `help` function.

In [59]:
help(arr.strides)

Help on tuple object:

class tuple(object)
 |  tuple() -> empty tuple
 |  tuple(iterable) -> tuple initialized from iterable's items
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  _

More generally, you can search for NumPy help on a variety of topics, using the `lookfor` function. 

In [100]:
np.lookfor('masked array') 

Search results for 'masked array'
---------------------------------
numpy.ma.array
    An array class with possibly masked values.
numpy.ma.asarray
    Convert the input to a masked array of the given data-type.
numpy.mafromtxt
    Load ASCII data stored in a text file and return a masked array.
numpy.ma.put
    Set storage-indexed locations to corresponding values.
numpy.ma.asanyarray
    Convert the input to a masked array, conserving subclasses.
numpy.ma.diag
    Extract a diagonal or construct a diagonal array.
numpy.ma.dump
    Pickle a masked array to a file.
numpy.ma.isMA
    Test whether input is an instance of MaskedArray.
numpy.ma.masked_all
    Empty masked array with all elements masked.
numpy.ma.count
    Count the non-masked elements of the array along the given axis.
numpy.ma.dumps
    Return a string corresponding to the pickling of a masked array.
numpy.ma.masked_less
    Mask an array where less than a given value.
numpy.ma.mvoid
    Fake a 'void' object to use for ma

## Array Operations

Arrays support all regular arithmetic operators, and the numpy library also contains a complete collection of basic mathematical functions that operate on arrays.  It is important to remember that in general, all operations with arrays are applied *element-wise*, i.e., are applied to all the elements of the array at the same time.  Consider for example:

In [60]:
arr1 = np.arange(4)
arr2 = np.arange(10, 14)
arr_sum = arr1 + arr2

print('{0} + {1} = {2}'.format(arr1, arr2, arr_sum))

[0 1 2 3] + [10 11 12 13] = [10 12 14 16]


Importantly, you must remember that even the multiplication operator is by default applied element-wise, it is *not* the matrix multiplication from linear algebra (as is the case in Matlab, for example):

In [61]:
print('{0} X {1} = {2}'.format(arr1, arr2, arr1*arr2))

[0 1 2 3] X [10 11 12 13] = [ 0 11 24 39]


While this means that in principle arrays must always match in their dimensionality in order for an operation to be valid, numpy will *broadcast* dimensions when possible.  For example, suppose that you want to add the number 1.5 to `arr1`; the following would be a valid way to do it:

In [62]:
arr1 + 1.5*np.ones(4)

array([ 1.5,  2.5,  3.5,  4.5])

But thanks to numpy's broadcasting rules, the following is equally valid:

In [63]:
arr1 + 1.5

array([ 1.5,  2.5,  3.5,  4.5])

In this case, numpy looked at both operands and saw that the first (`arr1`) was a one-dimensional array of length 4 and the second was a scalar, considered a zero-dimensional object. The broadcasting rules allow numpy to:

* *create* new dimensions of length 1 (since this doesn't change the size of the array)
* 'stretch' a dimension of length 1 that needs to be matched to a dimension of a different size.

So in the above example, the scalar 1.5 is effectively:

* first 'promoted' to a 1-dimensional array of length 1
* then, this array is 'stretched' to length 4 to match the dimension of `arr1`.

After these two operations are complete, the addition can proceed as now both operands are one-dimensional arrays of length 4.

This broadcasting behavior is in practice enormously powerful, especially because when numpy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually replicate the data.  In the example above the operation is carried *as if* the 1.5 was a 1-d array with 1.5 in all of its entries, but no actual array was ever created.  This can save lots of memory in cases when the arrays in question are large and can have significant performance implications.

The general rule is: when operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward, creating dimensions of length 1 as needed. Two dimensions are considered compatible when

* they are equal to begin with, or
* one of them is 1; in this case numpy will do the 'stretching' to make them equal.

If these conditions are not met, a `ValueError: frames are not aligned` exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

This shows how the broadcasting rules work in several dimensions:

In [113]:
b = np.array([2, 3, 4, 5])
bcast_sum = arr + b

print('{0}\n\n+ {1}\n{2}\n{3}'.format(arr, b, '-'*12, bcast_sum))

[[0 1 2 3]
 [4 5 6 7]]

+ [2 3 4 5]
------------
[[ 2  4  6  8]
 [ 6  8 10 12]]


Now, how could you use broadcasting to say add `[4, 6]` along the rows to `arr` above?  Simply performing the direct addition will produce the error we previously mentioned:

In [114]:
c = np.array([4, 6])
arr + c

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

According to the rules above, the array `c` would need to have a *trailing* dimension of 1 for the broadcasting to work.  It turns out that numpy allows you to 'inject' new dimensions anywhere into an array on the fly, by indexing it with the special object `np.newaxis`:

In [115]:
cplus = c[:, np.newaxis]
cplus

array([[4],
       [6]])

This is exactly what we need, and indeed it works:

In [116]:
arr + cplus

array([[ 4,  5,  6,  7],
       [10, 11, 12, 13]])

For the full broadcasting rules, please see the official Numpy docs, which describe them in detail and with more complex examples.

### Exercises

Generate the following structure as a numpy array, without typing the values by hand. Then, create another array containing just the 2nd and 4th rows.

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

In [68]:
# Write your answer here

Divide each column of the array:

        a = np.arange(25).reshape(5, 5)

elementwise with the array `b = np.array([1., 5, 10, 15, 20])`.


*Hint: `np.newaxis`*

In [69]:
# Write your answer here

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

*Hints*:

* Use `abs` and `argsort` to find the column `j` closest for each row.
* Use "fancy" indexing to extract the numbers.


In [70]:
# Write your answer here

## Linear Algebra

Numpy ships with a basic linear algebra library, and all arrays have a `dot` method whose behavior is that of the scalar dot product when its arguments are vectors (one-dimensional arrays) and the traditional matrix multiplication when one or both of its arguments are two-dimensional arrays:

In [85]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, 1])
dprod = v1.dot(v2)

print(v1, '.', v2, '=', dprod)

[2 3 4] . [1 0 1] = 6


There is an equivalent `dot` function:

In [86]:
np.dot(v1, v2)

6

Here is a regular matrix-vector multiplication, note that the array `v1` should be viewed as a *column* vector in traditional linear algebra notation; numpy makes no distinction between row and column vectors and simply verifies that the dimensions match the required rules of matrix multiplication, in this case we have a $2 \times 3$ matrix multiplied by a 3-vector, which produces a 2-vector:

In [87]:
A = np.arange(6).reshape(2, 3)
A.dot(v1)

array([11, 38])

For matrix-matrix multiplication, the same dimension-matching rules must be satisfied, e.g. consider the difference between $A \times A^T$:

In [88]:
A.dot(A.T)

array([[ 5, 14],
       [14, 50]])

and $A^T \times A$:

In [89]:
A.T.dot(A)

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

Furthermore, the `numpy.linalg` module includes additional functionality such as determinants, matrix norms, Cholesky, eigenvalue and singular value decompositions, etc.  For even more linear algebra tools, `scipy.linalg` contains the majority of the tools in the classic LAPACK libraries as well as functions to operate on sparse matrices.  We refer the reader to the Numpy and Scipy documentations for additional details on these.

## Reading and writing arrays to disk

Numpy lets you read and write arrays into files in a number of ways.  In order to use these tools well, it is critical to understand the difference between a *text* and a *binary* file containing numerical data.  In a text file, the number $\pi$ could be written as "3.141592653589793", for example: a string of digits that a human can read, with in this case 15 decimal digits.  In contrast, that same number written to a binary file would be encoded as 8 characters (bytes) that are not readable by a human but which contain the exact same data that the variable `pi` had in the computer's memory.  

The tradeoffs between the two modes are thus:

* **Text mode**: occupies more space, precision can be lost (if not all digits are written to disk), but is readable and editable by hand with a text editor.  Can *only* be used for one- and two-dimensional arrays.

* **Binary mode**: compact and exact representation of the data in memory, can't be read or edited by hand.  Arrays of any size and dimensionality can be saved and read without loss of information.

First, let's see how to read and write arrays in text mode.  The `np.savetxt` function saves an array to a text file, with options to control the precision, separators and even adding a header:

In [90]:
arr = np.arange(10).reshape(2, 5)
np.savetxt('test.out', arr, fmt='%.2e', header="My dataset")

In [91]:
!cat test.out

# My dataset
0.00e+00 1.00e+00 2.00e+00 3.00e+00 4.00e+00
5.00e+00 6.00e+00 7.00e+00 8.00e+00 9.00e+00


And this same type of file can then be read with the matching `np.loadtxt` function:

In [92]:
arr2 = np.loadtxt('test.out')
arr2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

For binary data, Numpy provides the `np.save` and `np.savez` routines.  The first saves a single array to a file with `.npy` extension, while the latter can be used to save a *group* of arrays into a single file with `.npz` extension.  The files created with these routines can then be read with the `np.load` function.

Let us first see how to use the simpler `np.save` function to save a single array:

In [93]:
np.save('test.npy', arr2)

# Now we read this back
arr2n = np.load('test.npy')

# Let's see if any element is non-zero in the difference.
# A value of True would be a problem.
np.any(arr2 - arr2n)

False

Now let us see how the `np.savez` function works.  You give it a filename and either a sequence of arrays or a set of keywords.  In the first mode, the function will auotmatically name the saved arrays in the archive as `arr_0`, `arr_1`, etc:

In [94]:
np.savez('test.npz', arr, arr2)
arrays = np.load('test.npz')
arrays.files

['arr_0', 'arr_1']

Alternatively, we can explicitly name the arrays we save using keyword arguments for `savez`:

In [95]:
np.savez('test.npz', array1=arr, array2=arr2)
arrays = np.load('test.npz')
arrays.files

['array1', 'array2']

The object returned by `np.load` from an `.npz` file works like a dictionary, though you can also access its constituent files by attribute using its special `.f` field; this is best illustrated with an example with the `arrays` object from above:

In [96]:
# First row of array
arrays['array1'][0]

array([0, 1, 2, 3, 4])

Equivalently:

In [97]:
arrays.f.array1[0]

array([0, 1, 2, 3, 4])

This `.npz` format is a very convenient way to package compactly and without loss of information, into a single file, a group of related arrays that pertain to a specific problem.  At some point, however, the complexity of your dataset may be such that the optimal approach is to use one of the standard formats in scientific data processing that have been designed to handle complex datasets, such as NetCDF or HDF5.  

---


In [84]:
from IPython.core.display import HTML
def css_styling():
    styles = open("styles/custom.css", "r").read()
    return HTML(styles)
css_styling()